# Generated by Django 5.2.17 on 2026-09-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Parser metadata (page count, attachments, OCR).'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pages',
            field=models.JSONField(blank=True, default=list, help_text='Page offsets into source_text; OCR pages also carry word boxes/confidence.'),
        ),
    ]
