# Generated by Django 5.2.17 on 2026-09-29 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_ocr_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionrun',
            name='examples',
            field=models.JSONField(blank=True, default=list, help_text='Verified documents used as few-shot examples.'),
        ),
        migrations.CreateModel(
            name='FieldReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('field', models.CharField(db_index=True, max_length=40)),
                ('extracted_value', models.TextField(blank=True, help_text="'' = not found by the model.")),
                ('approved_value', models.TextField(blank=True)),
                ('corrected', models.BooleanField(db_index=True, default=False)),
                ('extracted_confidence', models.FloatField(blank=True, null=True)),
                ('evidence_quote', models.TextField(blank=True, help_text='Where the approved value is printed on the document.')),
                ('reviewed_at', models.DateTimeField(db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reviews', to='documents.document')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_reviews', to='documents.vendor')),
            ],
            options={
                'ordering': ['-reviewed_at', 'document_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('document', 'field'), name='one_review_per_field')],
            },
        ),
    ]
